import { ExerciseDef } from './types';

export const EXERCISES: ExerciseDef[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'chest',
    type: 'strength',
    description: 'The king of chest exercises. A compound movement that targets the entire pectoralis major, anterior deltoid, and triceps.',
    primaryMuscles: ['Pectoralis Major', 'Anterior Deltoid', 'Triceps'],
    instructions: [
      'Lie flat on a bench, eyes under the bar.',
      'Grip the bar slightly wider than shoulder-width.',
      'Unrack the bar and lower it to mid-chest with control.',
      'Press back up explosively to full arm extension.',
    ],
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: 'chest',
    type: 'strength',
    description: 'Performed on an inclined bench (30-45°) to emphasize the upper chest and anterior deltoid more than the flat bench.',
    primaryMuscles: ['Upper Pectoralis Major', 'Anterior Deltoid', 'Triceps'],
    instructions: [
      'Set bench to 30-45° incline.',
      'Grip bar slightly wider than shoulder-width.',
      'Lower bar to upper chest, keeping elbows at ~75°.',
      'Press back to full extension.',
    ],
  },
  {
    id: 'dumbbell-chest-press',
    name: 'Dumbbell Chest Press',
    category: 'chest',
    type: 'strength',
    description: 'Allows a greater range of motion than the barbell press and helps correct strength imbalances between sides.',
    primaryMuscles: ['Pectoralis Major', 'Anterior Deltoid', 'Triceps'],
    instructions: [
      'Lie flat on a bench, dumbbells at chest level.',
      'Press both dumbbells up until arms are extended.',
      'Lower with control, feeling a stretch in the chest.',
    ],
  },
  {
    id: 'dumbbell-chest-fly',
    name: 'Dumbbell Chest Fly',
    category: 'chest',
    type: 'strength',
    description: 'An isolation movement that stretches and contracts the pectoral muscles through a wide arc.',
    primaryMuscles: ['Pectoralis Major'],
    instructions: [
      'Lie flat, holding dumbbells above chest with slight elbow bend.',
      'Open arms wide in a controlled arc until you feel a chest stretch.',
      'Squeeze the chest to bring the dumbbells back together.',
    ],
  },
  {
    id: 'cable-crossover',
    name: 'Cable Crossover',
    category: 'chest',
    type: 'strength',
    description: 'A cable isolation exercise that keeps constant tension on the pectorals throughout the movement.',
    primaryMuscles: ['Pectoralis Major', 'Anterior Deltoid'],
    instructions: [
      'Set cables at shoulder height or above.',
      'Step forward, grab handles, slight forward lean.',
      'Bring hands together in a hugging motion, squeezing the chest.',
      'Return slowly with control.',
    ],
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'chest',
    type: 'bodyweight',
    description: 'The fundamental bodyweight pushing exercise. Targets chest, shoulders, and triceps while also engaging the core.',
    primaryMuscles: ['Pectoralis Major', 'Anterior Deltoid', 'Triceps', 'Core'],
    instructions: [
      'Start in a plank position, hands slightly wider than shoulder-width.',
      'Lower your body until chest nearly touches the floor.',
      'Push back up to starting position.',
      'Keep your body in a straight line throughout.',
    ],
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'chest',
    type: 'strength',
    description: 'A guided pressing movement ideal for beginners or finishing sets, targeting the chest, shoulders, and triceps.',
    primaryMuscles: ['Pectoralis Major', 'Anterior Deltoid', 'Triceps'],
    instructions: [
      'Adjust seat so handles are at mid-chest level.',
      'Press handles forward until arms are extended.',
      'Return with control.',
    ],
  },

  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'back',
    type: 'strength',
    description: 'One of the most effective compound exercises. Targets the entire posterior chain — erectors, glutes, hamstrings, and traps.',
    primaryMuscles: ['Erector Spinae', 'Glutes', 'Hamstrings', 'Traps', 'Lats'],
    instructions: [
      'Stand with feet hip-width, bar over mid-foot.',
      'Hinge at hips, grip bar just outside legs.',
      'Brace core, keep back flat, drive through heels.',
      'Stand tall, then hinge back down with control.',
    ],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'back',
    type: 'bodyweight',
    description: 'A classic upper-body compound movement. Builds back width (lats) and biceps strength using bodyweight.',
    primaryMuscles: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoid'],
    instructions: [
      'Hang from a bar with an overhand grip, wider than shoulders.',
      'Pull yourself up until chin is above the bar.',
      'Lower with full control to a dead hang.',
    ],
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'back',
    type: 'bodyweight',
    description: 'Similar to pull-ups but with an underhand grip, placing more emphasis on the biceps.',
    primaryMuscles: ['Latissimus Dorsi', 'Biceps'],
    instructions: [
      'Hang from a bar with an underhand (supinated) grip, shoulder-width.',
      'Pull yourself up until chin clears the bar.',
      'Lower with control.',
    ],
  },
  {
    id: 'bent-over-row',
    name: 'Barbell Bent-Over Row',
    category: 'back',
    type: 'strength',
    description: 'A compound pulling movement that builds back thickness — targeting the mid-back, lats, and rear delts.',
    primaryMuscles: ['Rhomboids', 'Latissimus Dorsi', 'Rear Deltoid', 'Biceps'],
    instructions: [
      'Hinge forward ~45°, back flat, grip bar slightly wider than shoulder-width.',
      'Pull bar to lower chest/upper abdomen.',
      'Squeeze the shoulder blades at the top.',
      'Lower the bar with control.',
    ],
  },
  {
    id: 'dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    category: 'back',
    type: 'strength',
    description: 'Allows a great range of motion while targeting each side independently for balanced lat and mid-back development.',
    primaryMuscles: ['Latissimus Dorsi', 'Rhomboids', 'Biceps'],
    instructions: [
      'Place one knee and hand on a bench for support.',
      'Grab dumbbell with free hand, arm extended.',
      'Pull dumbbell to hip/lower rib, elbow tracking back.',
      'Lower with control.',
    ],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    type: 'strength',
    description: 'A machine-based pulling exercise that mimics the pull-up pattern, great for building lat width.',
    primaryMuscles: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoid'],
    instructions: [
      'Sit at the machine, grip the bar wider than shoulder-width.',
      'Lean back slightly, pull bar to upper chest.',
      'Squeeze lats at the bottom, then slowly return.',
    ],
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'back',
    type: 'strength',
    description: 'A horizontal pulling movement that targets mid-back thickness with constant cable tension.',
    primaryMuscles: ['Rhomboids', 'Latissimus Dorsi', 'Biceps'],
    instructions: [
      'Sit at cable row machine, feet on platform.',
      'Keep back upright, pull handle to lower chest.',
      'Squeeze shoulder blades together at the end.',
      'Return with control.',
    ],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'back',
    type: 'strength',
    description: 'A corrective and strengthening exercise for the rear deltoids and external rotators — great for shoulder health.',
    primaryMuscles: ['Rear Deltoid', 'External Rotators', 'Rhomboids'],
    instructions: [
      'Set cable at head height with rope attachment.',
      'Pull rope to face level, separating hands as you pull.',
      'Hold briefly, squeezing rear delts.',
      'Return with control.',
    ],
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    category: 'shoulders',
    type: 'strength',
    description: 'The primary compound shoulder exercise. Builds all three deltoid heads along with the triceps and upper chest.',
    primaryMuscles: ['Anterior Deltoid', 'Lateral Deltoid', 'Triceps'],
    instructions: [
      'Stand with feet shoulder-width, bar at clavicle level.',
      'Press the bar straight up overhead.',
      'Lock out at the top, then lower with control.',
    ],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    type: 'strength',
    description: 'A shoulder press variation with dumbbells that allows freer movement and helps address imbalances.',
    primaryMuscles: ['Anterior Deltoid', 'Lateral Deltoid', 'Triceps'],
    instructions: [
      'Sit or stand, dumbbells at shoulder height.',
      'Press both up until arms are fully extended.',
      'Lower back to shoulder height with control.',
    ],
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'shoulders',
    type: 'strength',
    description: 'A rotational shoulder press invented by Arnold Schwarzenegger. Targets all three deltoid heads through rotation.',
    primaryMuscles: ['Anterior Deltoid', 'Lateral Deltoid', 'Rear Deltoid'],
    instructions: [
      'Start with dumbbells in front of face, palms facing you.',
      'As you press up, rotate palms outward.',
      'Fully extend overhead, then reverse the motion on the way down.',
    ],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'shoulders',
    type: 'strength',
    description: 'The go-to isolation exercise for the lateral (middle) deltoid, creating shoulder width and the "capped" look.',
    primaryMuscles: ['Lateral Deltoid'],
    instructions: [
      'Stand holding dumbbells at sides.',
      'Raise arms out to the sides to shoulder height, slight elbow bend.',
      'Hold briefly at the top, then lower with control.',
    ],
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: 'shoulders',
    type: 'strength',
    description: 'Isolates the anterior (front) deltoid by raising the arm forward.',
    primaryMuscles: ['Anterior Deltoid'],
    instructions: [
      'Stand holding dumbbells or a plate in front.',
      'Raise arms forward to shoulder height.',
      'Lower with control.',
    ],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    category: 'shoulders',
    type: 'strength',
    description: 'Targets the often-neglected rear deltoid, important for posture and shoulder balance.',
    primaryMuscles: ['Rear Deltoid', 'Rhomboids'],
    instructions: [
      'Hinge forward or lie face-down on incline bench.',
      'Hold dumbbells, raise arms out to sides (like flapping wings).',
      'Squeeze rear delts at top, then lower.',
    ],
  },
  {
    id: 'shrugs',
    name: 'Barbell Shrugs',
    category: 'shoulders',
    type: 'strength',
    description: 'Isolates the trapezius muscles to build the upper-back/neck "shelf" look.',
    primaryMuscles: ['Trapezius'],
    instructions: [
      'Hold barbell in front of thighs with straight arms.',
      'Shrug shoulders straight up as high as possible.',
      'Hold briefly, then lower with control.',
    ],
  },

  // ── ARMS ───────────────────────────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'arms',
    type: 'strength',
    description: 'The classic bicep builder. Allows heavier loading than dumbbells for maximum bicep growth.',
    primaryMuscles: ['Biceps Brachii', 'Brachialis'],
    instructions: [
      'Stand holding barbell with underhand grip, shoulder-width.',
      'Keep elbows pinned to sides, curl bar to shoulder level.',
      'Squeeze biceps at top, then lower with control.',
    ],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'arms',
    type: 'strength',
    description: 'A versatile bicep exercise that allows independent arm movement and supination for full bicep contraction.',
    primaryMuscles: ['Biceps Brachii'],
    instructions: [
      'Stand or sit, dumbbells at sides.',
      'Curl one or both arms up, rotating palm up at the top.',
      'Squeeze and lower with control.',
    ],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'arms',
    type: 'strength',
    description: 'A neutral-grip curl that targets the brachialis and brachioradialis, adding arm thickness.',
    primaryMuscles: ['Brachialis', 'Brachioradialis', 'Biceps Brachii'],
    instructions: [
      'Hold dumbbells with a neutral grip (palms facing each other).',
      'Curl up while keeping neutral grip throughout.',
      'Lower with control.',
    ],
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'arms',
    type: 'strength',
    description: 'Performed on a preacher bench to isolate the biceps and prevent cheating.',
    primaryMuscles: ['Biceps Brachii'],
    instructions: [
      'Sit at preacher bench, upper arms flat on pad.',
      'Curl bar or dumbbell up, squeezing at top.',
      'Lower fully for maximum stretch.',
    ],
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'arms',
    type: 'strength',
    description: 'A lying tricep extension that heavily targets all three tricep heads with a great stretch at the bottom.',
    primaryMuscles: ['Triceps Brachii'],
    instructions: [
      'Lie on bench, hold EZ-bar or dumbbells above chest.',
      'Bend elbows, lowering weight toward forehead.',
      'Extend arms back to starting position.',
    ],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    category: 'arms',
    type: 'strength',
    description: 'A cable isolation exercise that targets the triceps with constant tension.',
    primaryMuscles: ['Triceps Brachii'],
    instructions: [
      'Stand at cable machine with rope or bar attachment at head height.',
      'Keep elbows at sides, push down until arms are fully extended.',
      'Slowly return to starting position.',
    ],
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'arms',
    type: 'strength',
    description: 'Extends the triceps overhead for maximum long-head stretch and activation.',
    primaryMuscles: ['Triceps Brachii (long head)'],
    instructions: [
      'Hold dumbbell or EZ-bar overhead with both hands.',
      'Lower weight behind head by bending elbows.',
      'Extend arms back to full extension.',
    ],
  },
  {
    id: 'tricep-dip',
    name: 'Tricep Dip',
    category: 'arms',
    type: 'bodyweight',
    description: 'A bodyweight compound movement that powerfully targets the triceps, chest, and anterior deltoid.',
    primaryMuscles: ['Triceps Brachii', 'Anterior Deltoid', 'Pectoralis Major'],
    instructions: [
      'Grip parallel bars or bench behind you.',
      'Lower body by bending elbows to ~90°.',
      'Press back up to full arm extension.',
    ],
  },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    category: 'legs',
    type: 'strength',
    description: 'The foundational lower-body exercise. Targets quads, glutes, hamstrings, and core as a complete lower body builder.',
    primaryMuscles: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
    instructions: [
      'Bar rests on upper traps, feet shoulder-width.',
      'Brace core, push knees out, descend to parallel or below.',
      'Drive through heels to stand back up.',
    ],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'legs',
    type: 'strength',
    description: 'A machine-based lower body exercise allowing heavy loading with less spinal stress than squats.',
    primaryMuscles: ['Quadriceps', 'Glutes', 'Hamstrings'],
    instructions: [
      'Sit in the machine, feet shoulder-width on the platform.',
      'Lower the platform until knees are at ~90°.',
      "Press back to full extension (don't lock out knees).",
    ],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    type: 'strength',
    description: 'A hip-hinge movement that heavily targets the hamstrings and glutes through an extended stretch.',
    primaryMuscles: ['Hamstrings', 'Glutes', 'Erector Spinae'],
    instructions: [
      'Hold bar at hip level, soft knee bend.',
      'Hinge at hips, lowering bar along legs.',
      'Feel a deep hamstring stretch at the bottom.',
      'Drive hips forward to return to standing.',
    ],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    type: 'strength',
    description: 'A single-leg squat variation with back foot elevated, providing intense quad and glute stimulus.',
    primaryMuscles: ['Quadriceps', 'Glutes', 'Hamstrings'],
    instructions: [
      'Rear foot elevated on bench, front foot ~2 feet forward.',
      'Hold dumbbells at sides.',
      'Lower front knee toward the floor.',
      'Drive back up through front heel.',
    ],
  },
  {
    id: 'lunges',
    name: 'Lunges',
    category: 'legs',
    type: 'strength',
    description: 'A unilateral exercise that develops leg strength, stability, and balance while targeting quads and glutes.',
    primaryMuscles: ['Quadriceps', 'Glutes', 'Hamstrings'],
    instructions: [
      'Step forward with one foot into a lunge position.',
      'Lower back knee toward the floor.',
      'Push off front foot to return to standing, or alternate legs.',
    ],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'legs',
    type: 'strength',
    description: 'A machine isolation exercise targeting the quadriceps through knee extension.',
    primaryMuscles: ['Quadriceps'],
    instructions: [
      'Sit in machine, pad resting on shins.',
      'Extend legs until straight, squeezing quads at top.',
      'Lower with control.',
    ],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: 'legs',
    type: 'strength',
    description: 'A machine isolation exercise for the hamstrings performed lying or seated.',
    primaryMuscles: ['Hamstrings'],
    instructions: [
      'Lie prone (or sit) in machine, pad behind ankles.',
      'Curl legs up, squeezing hamstrings.',
      'Lower with control.',
    ],
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'legs',
    type: 'strength',
    description: 'Targets the gastrocnemius and soleus (calves) through plantarflexion.',
    primaryMuscles: ['Gastrocnemius', 'Soleus'],
    instructions: [
      'Stand on edge of step or flat ground, balls of feet on edge.',
      'Rise up on toes as high as possible.',
      'Lower heels below step level for a full stretch.',
    ],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'legs',
    type: 'strength',
    description: 'The most effective glute isolation exercise, producing maximum glute activation.',
    primaryMuscles: ['Glutes', 'Hamstrings'],
    instructions: [
      'Sit with upper back against bench, bar across hips.',
      'Drive hips up until body forms a straight line.',
      'Squeeze glutes hard at the top, then lower.',
    ],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'legs',
    type: 'strength',
    description: 'A front-loaded squat variation holding a dumbbell or kettlebell, excellent for quad and glute development.',
    primaryMuscles: ['Quadriceps', 'Glutes', 'Core'],
    instructions: [
      'Hold dumbbell/kettlebell at chest level.',
      'Squat down, pushing knees out.',
      'Drive through heels to stand.',
    ],
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    type: 'timed',
    description: 'The fundamental isometric core exercise. Builds anti-extension strength and overall core stability.',
    primaryMuscles: ['Rectus Abdominis', 'Transverse Abdominis', 'Obliques'],
    instructions: [
      'Place forearms on ground, body in a straight line.',
      'Brace core hard, squeeze glutes.',
      'Hold for the target duration.',
    ],
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'core',
    type: 'bodyweight',
    description: 'The classic abdominal exercise targeting the rectus abdominis through spinal flexion.',
    primaryMuscles: ['Rectus Abdominis'],
    instructions: [
      'Lie on back, knees bent, hands behind head.',
      'Curl upper back off the floor, squeezing abs.',
      'Lower with control.',
    ],
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    type: 'bodyweight',
    description: 'A rotational exercise targeting the obliques and transverse abdominis.',
    primaryMuscles: ['Obliques', 'Transverse Abdominis'],
    instructions: [
      'Sit with knees bent, lean back slightly, feet off floor.',
      'Rotate torso side to side.',
      'Can hold a weight for added resistance.',
    ],
  },
  {
    id: 'leg-raise',
    name: 'Leg Raise',
    category: 'core',
    type: 'bodyweight',
    description: 'Targets the lower abdominals and hip flexors through leg raising from a hanging or lying position.',
    primaryMuscles: ['Lower Rectus Abdominis', 'Hip Flexors'],
    instructions: [
      'Lie flat or hang from a bar.',
      'Raise legs to 90° while keeping them straight.',
      'Lower with control without touching the floor.',
    ],
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: 'core',
    type: 'strength',
    description: 'A weighted crunch using a cable machine for progressive overload on the abs.',
    primaryMuscles: ['Rectus Abdominis'],
    instructions: [
      'Kneel at cable machine with rope overhead.',
      'Crunch down, pulling elbows toward knees.',
      'Squeeze abs at bottom, return with control.',
    ],
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    category: 'core',
    type: 'bodyweight',
    description: 'An advanced anti-extension exercise that builds incredible core stability and strength.',
    primaryMuscles: ['Rectus Abdominis', 'Transverse Abdominis', 'Lats'],
    instructions: [
      'Kneel with ab wheel on the floor.',
      'Roll forward, keeping hips extended, until body is parallel to floor.',
      'Use core to pull back to starting position.',
    ],
  },

  // ── CARDIO ─────────────────────────────────────────────────────────────────
  {
    id: 'running',
    name: 'Running',
    category: 'cardio',
    type: 'cardio',
    description: 'One of the most accessible forms of cardio. Improves cardiovascular fitness, burns calories, and builds endurance.',
    primaryMuscles: ['Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Cardiovascular System'],
    instructions: [
      'Warm up with a 5-minute walk.',
      'Run at a comfortable pace, maintain upright posture.',
      'Land mid-foot, not heel-striking.',
    ],
  },
  {
    id: 'cycling',
    name: 'Cycling',
    category: 'cardio',
    type: 'cardio',
    description: 'Low-impact cardiovascular training on a stationary or outdoor bike.',
    primaryMuscles: ['Quadriceps', 'Hamstrings', 'Glutes', 'Cardiovascular System'],
    instructions: [
      'Adjust seat so leg has slight bend at bottom of pedal stroke.',
      'Maintain a cadence of 70-100 RPM.',
      'Control intensity with resistance.',
    ],
  },
  {
    id: 'rowing',
    name: 'Rowing Machine',
    category: 'cardio',
    type: 'cardio',
    description: 'A full-body cardio exercise using 86% of your muscles. Excellent for both cardiovascular fitness and upper body endurance.',
    primaryMuscles: ['Back', 'Legs', 'Arms', 'Cardiovascular System'],
    instructions: [
      'Start with legs bent, arms extended (catch position).',
      'Push with legs first, then lean back, then pull arms.',
      'Return: arms first, then lean forward, then bend legs.',
    ],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    type: 'cardio',
    description: 'High-intensity cardio that improves coordination, timing, and cardiovascular capacity.',
    primaryMuscles: ['Calves', 'Cardiovascular System', 'Shoulders'],
    instructions: [
      'Hold handles at hip level, elbows slightly bent.',
      'Jump with both feet, keeping hops small.',
      'Use wrists to turn the rope, not arms.',
    ],
  },
  {
    id: 'elliptical',
    name: 'Elliptical',
    category: 'cardio',
    type: 'cardio',
    description: 'Low-impact cardio machine that mimics running without the joint stress.',
    primaryMuscles: ['Quadriceps', 'Hamstrings', 'Glutes', 'Cardiovascular System'],
    instructions: [
      'Step onto pedals, grip handles.',
      'Pedal in an elliptical motion, keeping feet flat.',
      'Use arms to engage upper body.',
    ],
  },
  {
    id: 'stair-climber',
    name: 'Stair Climber',
    category: 'cardio',
    type: 'cardio',
    description: 'Simulates stair climbing for cardiovascular training and lower body conditioning.',
    primaryMuscles: ['Glutes', 'Quadriceps', 'Calves', 'Cardiovascular System'],
    instructions: [
      'Set desired speed/resistance.',
      'Maintain upright posture, light grip on rails.',
      'Take full steps, pushing through entire foot.',
    ],
  },
];

export const EXERCISE_MAP = new Map<string, ExerciseDef>(
  EXERCISES.map((e) => [e.id, e])
);

export const CATEGORIES: { id: string; label: string; emoji: string }[] = [
  { id: 'chest', label: 'Chest', emoji: '🏋️' },
  { id: 'back', label: 'Back', emoji: '🔙' },
  { id: 'shoulders', label: 'Shoulders', emoji: '🔝' },
  { id: 'arms', label: 'Arms', emoji: '💪' },
  { id: 'legs', label: 'Legs', emoji: '🦵' },
  { id: 'core', label: 'Core', emoji: '🎯' },
  { id: 'cardio', label: 'Cardio', emoji: '🏃' },
];
